// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package slot

import (
	"io"

	"github.com/KonjacBot/go-mc/net/packet"
)

func (c *Item) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Item) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ItemStack) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.ItemStack).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ItemStack) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.ItemStack).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *Tag) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Tag).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Tag) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Tag).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *SmithingTrimData) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.AssetId).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Description).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.Decal).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c SmithingTrimData) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.AssetId).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Description).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.Decal).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *SmithingTrim) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Base).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Material).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Pattern).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c SmithingTrim) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Base).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Material).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Pattern).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *WithRemainder) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Ingredient).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Remainder).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c WithRemainder) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Ingredient).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Remainder).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *Composite) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Displays).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Composite) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Displays).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
