// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package server

import (
	"io"

	"github.com/KonjacBot/go-mc/net/packet"
	"github.com/KonjacBot/minego/pkg/protocol/packet/codecutil"
)

func (c *ConfigCustomClickAction) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Action).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = codecutil.LengthPrefixedNBT{Value: &c.Data, MaxLen: 65536}.ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigCustomClickAction) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Identifier)(&c.Action).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = codecutil.LengthPrefixedNBT{Value: &c.Data, MaxLen: 65536}.WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigFinishConfiguration) ReadFrom(r io.Reader) (n int64, err error) {
	return 0, nil
}

func (c ConfigFinishConfiguration) WriteTo(w io.Writer) (n int64, err error) {
	return 0, nil
}
func (c *ConfigKeepAlive) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Long)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigKeepAlive) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Long)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigPong) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Int)(&c.ID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigPong) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Int)(&c.ID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ConfigSelectKnownPacks) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Packs).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ConfigSelectKnownPacks) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Packs).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
