// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package slot

import (
	"errors"
	"io"

	"github.com/KonjacBot/go-mc/net/packet"
)

func (c *AddedHashedComponent) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Int)(&c.DataHash).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c AddedHashedComponent) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Int)(&c.DataHash).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *HashedSlot) ReadFrom(r io.Reader) (n int64, err error) {
	*c = HashedSlot{}
	var temp int64
	temp, err = (*packet.Boolean)(&c.HasItem).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if c.HasItem {
		temp, err = (*packet.VarInt)(&c.ItemID).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.HasItem {
		temp, err = (*packet.VarInt)(&c.ItemCount).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.HasItem {
		var size packet.VarInt
		temp, err = size.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		if size < 0 {
			return n, errors.New("array length less than zero")
		}
		if size > 256 {
			return n, errors.New("array length greater than 256")
		}
		if cap(c.AddComponents) >= int(size) {
			c.AddComponents = c.AddComponents[:int(size)]
		} else {
			c.AddComponents = make([]AddedHashedComponent, int(size))
		}
		for i := range c.AddComponents {
			temp, err = (&c.AddComponents[i]).ReadFrom(r)
			n += temp
			if err != nil {
				return n, err
			}
		}
	}
	if c.HasItem {
		var size packet.VarInt
		temp, err = size.ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
		if size < 0 {
			return n, errors.New("array length less than zero")
		}
		if size > 256 {
			return n, errors.New("array length greater than 256")
		}
		if cap(c.RemovedComponents) >= int(size) {
			c.RemovedComponents = c.RemovedComponents[:int(size)]
		} else {
			c.RemovedComponents = make([]int32, int(size))
		}
		for i := range c.RemovedComponents {
			temp, err = (*packet.VarInt)(&c.RemovedComponents[i]).ReadFrom(r)
			n += temp
			if err != nil {
				return n, err
			}
		}
	}
	return n, nil
}

func (c HashedSlot) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Boolean)(&c.HasItem).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	if c.HasItem {
		temp, err = (*packet.VarInt)(&c.ItemID).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.HasItem {
		temp, err = (*packet.VarInt)(&c.ItemCount).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.HasItem {
		if len(c.AddComponents) > 256 {
			return n, errors.New("array length greater than 256")
		}
		temp, err = packet.VarInt(len(c.AddComponents)).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		for i := range c.AddComponents {
			temp, err = (&c.AddComponents[i]).WriteTo(w)
			n += temp
			if err != nil {
				return n, err
			}
		}
	}
	if c.HasItem {
		if len(c.RemovedComponents) > 256 {
			return n, errors.New("array length greater than 256")
		}
		temp, err = packet.VarInt(len(c.RemovedComponents)).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
		for i := range c.RemovedComponents {
			temp, err = packet.VarInt(c.RemovedComponents[i]).WriteTo(w)
			n += temp
			if err != nil {
				return n, err
			}
		}
	}
	return n, nil
}

// Int32VarIntVarIntArray a utility type for encoding/decoding packet.VarInt -> int32[packet.VarInt] slice.
type Int32VarIntVarIntArray []int32

func (a Int32VarIntVarIntArray) WriteTo(w io.Writer) (n int64, err error) {
	size := len(a)
	nn, err := packet.VarInt(size).WriteTo(w)
	if err != nil {
		return n, err
	}
	n += nn
	for i := 0; i < size; i++ {
		nn, err := packet.VarInt(a[i]).WriteTo(w)
		n += nn
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (a *Int32VarIntVarIntArray) ReadFrom(r io.Reader) (n int64, err error) {
	var size packet.VarInt
	nn, err := size.ReadFrom(r)
	n += nn
	if err != nil {
		return n, err
	}
	if size < 0 {
		return n, errors.New("array length less than zero")
	}

	if size > 32767 {
		return n, errors.New("array length greater than 32767")
	}

	if cap(*a) >= int(size) {
		*a = (*a)[:int(size)]
	} else {
		*a = make(Int32VarIntVarIntArray, int(size))
	}

	for i := 0; i < int(size); i++ {
		nn, err = (*packet.VarInt)(&(*a)[i]).ReadFrom(r)
		n += nn
		if err != nil {
			return n, err
		}
	}

	return n, err
}
