// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package protocol

import (
	"io"

	"github.com/KonjacBot/go-mc/net/packet"
)

func (c *GameProfile) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.UUID)(&c.UUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Name).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c GameProfile) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.UUID)(&c.UUID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.String)(&c.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *PartialProfile) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Username).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.UUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c PartialProfile) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Username).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.UUID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Properties).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ResolvableProfile) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if c.Type == 0 {
		c.Partial = new(PartialProfile)
		temp, err = (*PartialProfile)(c.Partial).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.Type == 1 {
		c.GameProfile = new(ResolvableProfile)
		temp, err = (*ResolvableProfile)(c.GameProfile).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	temp, err = (&c.Body).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Cape).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Elytra).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Model).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ResolvableProfile) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	if c.Type == 0 {
		temp, err = (*PartialProfile)(c.Partial).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.Type == 1 {
		temp, err = (*ResolvableProfile)(c.GameProfile).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	temp, err = (&c.Body).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Cape).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Elytra).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Model).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
