// Code generated by github.com/go-mc/packetizer; DO NOT EDIT.

package metadata

import (
	"io"

	"github.com/KonjacBot/go-mc/net/packet"
	"github.com/KonjacBot/minego/pkg/protocol"
)

func (c *Rotation) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Rotation) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *NBT) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = packet.NBT(&c.Data).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c NBT) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = packet.NBT(&c.Data).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *Particles) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Particles).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Particles) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = packet.Array(&c.Particles).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *VillagerData) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Profession).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Level).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c VillagerData) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.VarInt)(&c.Type).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Profession).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.VarInt)(&c.Level).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *GlobalPosition) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.Dimension).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Position).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c GlobalPosition) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.Dimension).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Position).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *OptGlobalPosition) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (&c.GlobalPosition).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c OptGlobalPosition) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (&c.GlobalPosition).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *Vector3) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Vector3) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *Quaternion) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.W).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c Quaternion) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Float)(&c.X).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Y).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.Z).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Float)(&c.W).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ResolvableProfilePartial) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Name).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.UUID)(&c.UUID).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Property).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ResolvableProfilePartial) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.String)(&c.Name).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.UUID)(&c.UUID).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = packet.Array(&c.Property).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
func (c *ResolvableProfile) ReadFrom(r io.Reader) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Boolean)(&c.IsFullProfile).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	if c.IsFullProfile == true {
		c.Profile = new(protocol.GameProfile)
		temp, err = (*protocol.GameProfile)(c.Profile).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.IsFullProfile == false {
		c.Partial = new(ResolvableProfilePartial)
		temp, err = (*ResolvableProfilePartial)(c.Partial).ReadFrom(r)
		n += temp
		if err != nil {
			return n, err
		}
	}
	temp, err = (&c.Body).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Cape).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Elytra).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.Model).ReadFrom(r)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}

func (c ResolvableProfile) WriteTo(w io.Writer) (n int64, err error) {
	var temp int64
	temp, err = (*packet.Boolean)(&c.IsFullProfile).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	if c.IsFullProfile == true {
		temp, err = (*protocol.GameProfile)(c.Profile).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	if c.IsFullProfile == false {
		temp, err = (*ResolvableProfilePartial)(c.Partial).WriteTo(w)
		n += temp
		if err != nil {
			return n, err
		}
	}
	temp, err = (&c.Body).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Cape).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (&c.Elytra).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	temp, err = (*packet.Boolean)(&c.Model).WriteTo(w)
	n += temp
	if err != nil {
		return n, err
	}
	return n, err
}
